import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

import { THEME } from "@excalidraw/common";

import * as icons from "../../excalidraw/components/icons";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.resolve(scriptDir, "../src/components/icons.generated.ts");

type IconVariant = { suffix: string; props: Record<string, unknown> };

const themeVariants: IconVariant[] = [
  { suffix: "Light", props: { theme: THEME.LIGHT } },
  { suffix: "Dark", props: { theme: THEME.DARK } },
];

const flipVariants: IconVariant[] = [
  { suffix: "", props: { flip: false } },
  { suffix: "Flipped", props: { flip: true } },
];

const arrowheadIconNames = [
  "ArrowheadNoneIcon",
  "ArrowheadArrowIcon",
  "ArrowheadTriangleIcon",
  "ArrowheadTriangleOutlineIcon",
  "ArrowheadCircleIcon",
  "ArrowheadCircleOutlineIcon",
  "ArrowheadDiamondIcon",
  "ArrowheadDiamondOutlineIcon",
  "ArrowheadBarIcon",
  "ArrowheadCardinalityOneIcon",
  "ArrowheadCardinalityManyIcon",
  "ArrowheadCardinalityOneOrManyIcon",
  "ArrowheadCardinalityExactlyOneIcon",
  "ArrowheadCardinalityZeroOrOneIcon",
  "ArrowheadCardinalityZeroOrManyIcon",
];

const paramIconVariants: Record<string, IconVariant[]> = {
  GroupIcon: themeVariants,
  UngroupIcon: themeVariants,
  TextAlignTopIcon: themeVariants,
  TextAlignBottomIcon: themeVariants,
  TextAlignMiddleIcon: themeVariants,
};
for (const name of arrowheadIconNames) {
  paramIconVariants[name] = flipVariants;
}

// ng-icons resolves <ng-icon name> through its own toPropertyName(), which
// lowercases the first character before looking the key up in the provided
// map. Registering keys any other way makes name-based lookups silently
// fail, so the generated keys are the upstream export names with only the
// first character lowercased (matching what ng-icons will look for).
const toRegistryKey = (name: string) =>
  name.charAt(0).toLowerCase() + name.slice(1);

const generated: Record<string, string> = {};
const skipped: string[] = [];
const materialized: string[] = [];
const renamed: string[] = [];

// Two upstream exports can collide once transformed (e.g. `HelpIcon` and
// `helpIcon` both become "helpIcon"). Keep the first one under its natural
// key and suffix later ones deterministically rather than dropping either.
const addIcon = (sourceName: string, svg: string) => {
  const baseKey = toRegistryKey(sourceName);
  let key = baseKey;
  let attempt = 2;
  while (key in generated) {
    key = `${baseKey}${attempt}`;
    attempt += 1;
  }
  if (key !== baseKey) {
    renamed.push(`${sourceName} -> ${key} (collides with ${baseKey})`);
  }
  generated[key] = svg;
};

for (const [name, value] of Object.entries(icons).sort(([a], [b]) =>
  a < b ? -1 : a > b ? 1 : 0,
)) {
  if (React.isValidElement(value)) {
    addIcon(name, renderToStaticMarkup(value));
    continue;
  }

  const variants = paramIconVariants[name];
  if (variants) {
    for (const { suffix, props } of variants) {
      const element = React.createElement(
        value as React.ComponentType<Record<string, unknown>>,
        props,
      );
      addIcon(`${name}${suffix}`, renderToStaticMarkup(element));
    }
    materialized.push(name);
    continue;
  }

  skipped.push(name);
}

const sortedEntries = Object.entries(generated).sort(([a], [b]) =>
  a < b ? -1 : a > b ? 1 : 0,
);

const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const body = sortedEntries
  .map(([name, svg]) => {
    if (!identifierPattern.test(name)) {
      throw new Error(`generated icon key "${name}" is not a valid identifier`);
    }
    if (svg.includes("'")) {
      throw new Error(
        `icon "${name}" contains a single quote in its svg markup`,
      );
    }
    return `  ${name}: '${svg}',`;
  })
  .join("\n");

const output = `// generated by packages/caliburn/scripts/generate-icons.mts — do not edit
export const caliburnIcons: Record<string, string> = {
${body}
};
`;

writeFileSync(outFile, output);

console.log(`wrote ${sortedEntries.length} icons to ${outFile}`);
console.log(
  `materialized ${materialized.length} parameterized icons: ${materialized.join(
    ", ",
  )}`,
);
console.log(`skipped ${skipped.length} exports: ${skipped.join(", ")}`);
if (renamed.length > 0) {
  console.log(
    `renamed ${renamed.length} colliding keys: ${renamed.join(", ")}`,
  );
}
